[package]
name = "flux"
version = "0.1.0"
authors = ["phil"]
edition = "2018"

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.5"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
structopt = "0.2.10"
